# version: '3.8'

services:
  web:
    command: sh -c "cd /app/ft_transcendence && python manage.py migrate && python manage.py collectstatic --noinput --clear && daphne -p 8000 -b 0.0.0.0 ft_transcendence.asgi:application"
    environment:
      - DJANGO_SETTINGS_MODULE=ft_transcendence.settings.prod
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx-prod
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/www:/var/www/html
      - ./staticfiles:/app/staticfiles:ro
      - ./ft_transcendence/media:/app/media:ro
    ports:
      - "8000:8000"
    depends_on:
      - web
    networks:
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/www:/var/www/html
    command: certonly --non-interactive --webroot --webroot-path=/var/www/certbot --email your-email@example.com --agree-tos --no-eff-email -d louismdv.works