# version: '3.8'

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 ft_transcendence.asgi:application
    environment:
      - DJANGO_SETTINGS_MODULE=ft_transcendence.settings.dev
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"   # Expose Django dev server
    volumes:
      - .:/app
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - ./ft_transcendence/static:/app/ft_transcendence/static
      - ./ft_transcendence/media:/app/ft_transcendence/media
    depends_on:
      - web
    networks:
      - backend