# version: '3.8'

services:
  web:
    build: .
    command: sh -c "cd /app/ft_transcendence && python manage.py migrate && python manage.py collectstatic --noinput --clear && daphne -p 8000 -b 0.0.0.0 ft_transcendence.asgi:application"
    environment:
      - DJANGO_SETTINGS_MODULE=ft_transcendence.settings.prod
      - PYTHONUNBUFFERED=1
    networks:
      - backend

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.test.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./staticfiles:/app/staticfiles:ro
      - ./ft_transcendence/media:/app/media:ro
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
    depends_on:
      - web
    networks:
      - backend

networks:
  backend:
    driver: bridge