# Generated by Django 5.1.7 on 2025-04-24 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='created_at',
        ),
    ]
