# Generated by Django 3.2.25 on 2025-04-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_transcendence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_activity',
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=2),
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
