# Generated by Django 3.2.25 on 2025-05-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_transcendence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='../static/assets/default.png', null=True, upload_to='avatars/'),
        ),
    ]
