# Generated by Django 3.2.25 on 2025-04-28 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ft_transcendence', '0002_gameroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameRoom',
        ),
    ]
