# Generated by Django 3.2.25 on 2025-04-23 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ft_transcendence', '0003_auto_20250421_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_activity',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
