# Generated by Django 3.2.25 on 2025-04-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_transcendence', '0005_auto_20250423_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_games',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tournaments_won',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='win_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
