# Generated by Django 3.2.25 on 2025-04-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ft_transcendence', '0006_auto_20250427_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='total_games',
            new_name='total_local_games',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='tournaments_won',
            new_name='total_online_games',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='win_rate',
        ),
    ]
